### PR TITLE
Improve the query cli to make it easier to use.

### PR DESCRIPTION
**Pull request by kentquirk**
@jhbate - see what you think?

### CODE REVIEW

**Comment by jh-bate** [comment]
cool - I will test it tonight

**Comment by kentquirk** [comment]
@jh-bate -- ping? I'd love to merge this.

**Comment by jh-bate** [comment]
crap - sorry totally dropped the ball. Just doing it now

**Comment by jh-bate** [comment]
LGTM esp the help after not using this for a while :)

**Pull request merged**
